// <auto-generated />
namespace CoffeeMachine.Infrastructure.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class User_UserIdentifier : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(User_UserIdentifier));
        
        string IMigrationMetadata.Id
        {
            get { return "201702052015401_User_UserIdentifier"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
